spring.application.name=users-service

spring.datasource.url=jdbc:postgresql://localhost:5432/users
spring.datasource.username=app
spring.datasource.password=app
spring.datasource.driver-class-name=org.postgresql.Driver
management.endpoints.web.exposure.include=health,prometheus,info
management.metrics.tags.application=${spring.application.name}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.shomanagement.tracing.sampling.probability=1.0
management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/tracesw-sql=true