spring.application.name=api-gateway
server.port=8000

spring.cloud.compatibility-verifier.enabled=false

spring.cloud.gateway.server.webmvc.routes[0].id=users-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://users-service:8080
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/users/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webmvc.routes[1].id=products-service
spring.cloud.gateway.server.webmvc.routes[1].uri=http://products-service:8081
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/products/**
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webmvc.routes[2].id=orders-service
spring.cloud.gateway.server.webmvc.routes[2].uri=http://orders-service:8082
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/orders/**
spring.cloud.gateway.server.webmvc.routes[2].filters[0]=StripPrefix=1

management.endpoints.web.exposure.include=health,prometheus,info
management.metrics.tags.application=${spring.application.name}
management.tracing.sampling.probability=1.0
management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces