spring.application.name=products-service

spring.datasource.url=jdbc:postgresql://localhost:5434/products
spring.datasource.username=app
spring.datasource.password=app
spring.datasource.driver-class-name=org.postgresql.Driver
management.endpoints.web.exposure.include=health,prometheus,info
management.metrics.tags.application=${spring.application.name}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081